name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  provision:
    name: Provision Resources and Deploy App
    runs-on: ubuntu-latest
    environment: prod
    env:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }} 
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}  
      AUTH_APP_ID: ${{ secrets.AUTH_APP_ID }}
      AUTH_CLIENT_ID: ${{ secrets.AUTH_CLIENT_ID }}
      AUTH_CLIENT_SECRET: ${{ secrets.AUTH_CLIENT_SECRET }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure Dev CLI
        uses: Azure/setup-azd@v1.0.0
        with:
          version: latest

      - name: Login to Azure Dev CLI 
        shell: bash
        run: |
          echo "Logging to Azure Developer CLI..."
          AZURE_CREDENTIALS=$(echo "$AZURE_CREDENTIALS" | jq -r .)
          CLIENT_ID=$(echo $AZURE_CREDENTIALS | jq -r .clientId)
          CLIENT_SECRET=$(echo $AZURE_CREDENTIALS | jq -r .clientSecret)
          TENANT_ID=$(echo $AZURE_CREDENTIALS | jq -r .tenantId)
          azd auth login --client-id $CLIENT_ID --client-secret $CLIENT_SECRET --tenant-id $TENANT_ID    

      - name: azd init
        shell: bash
        run: |
         azd init -e $AZURE_ENV_NAME  -l $AZURE_LOCATION -s $AZURE_SUBSCRIPTION_ID
         azd env set AUTH_APP_ID $AUTH_APP_ID
         azd env set AUTH_CLIENT_ID $AUTH_CLIENT_ID
         azd env set AUTH_CLIENT_SECRET $AUTH_CLIENT_SECRET

      - name: azd provision
        shell: bash
        run: azd provision

      - name: azd deploy
        shell: bash
        run: azd deploy