name: Deploy to Production

on:
  push:
    branches:
      - develop

jobs:
  provision:
    name: Provision Azure Resources
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure Dev CLI
        uses: Azure/setup-azd@v1.0.0
        with:
          version: latest

      - name: azd init
        shell: bash
        run: azd init -e ${{ env.AZURE_ENV_NAME }} -l ${{ env.AZURE_LOCATION }} -s ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: azd provision
        shell: bash
        run: azd provision

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    environment: dev
    needs: provision
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure Dev CLI
        uses: Azure/setup-azd@v1.0.0
        with:
          version: latest

      - name: azd deploy
        shell: bash
        run: azd deploy
