name: PR Pipeline

on:
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:

  backend:
    runs-on:
    - ubuntu-latest
    environment: dev    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        echo "Install dependencies"
    - name: Test with pytest
      run: |
        echo "Test with pytest"
        export PYTHONPATH=$(pwd)
        coverage run -m pytest -v tests/test_app.py --show-capture=stdout
        # coverage run -m pytest -v --show-capture=stdout
        coverage report -m --include=app.py,backend/*,tests/*
        coverage xml

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '50 80'

  frontend:
    runs-on: ubuntu-latest
    environment: dev    
    defaults:
      run:
        working-directory: frontend
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 21.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - run: npm ci
    - run: NODE_OPTIONS=--max_old_space_size=8192 npm run build --if-present
    - run: npm run test --if-present        